import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  Search,
  BookOpen,
  BarChart3,
  Briefcase,
  CreditCard,
  ChevronDown,
  Mail,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Mock data
// ---------------------------------------------------------------------------

const categories = [
  {
    icon: BookOpen,
    title: "Getting Started",
    articles: 5,
    description:
      "Learn the basics of Takovic, set up your account, and explore core features.",
  },
  {
    icon: BarChart3,
    title: "Stock Analysis",
    articles: 8,
    description:
      "Understand Snowflake Scores, AI insights, valuation tools, and financial data.",
  },
  {
    icon: Briefcase,
    title: "Portfolio & Watchlists",
    articles: 6,
    description:
      "Create and manage portfolios, set up watchlists, and track performance.",
  },
  {
    icon: CreditCard,
    title: "Account & Billing",
    articles: 4,
    description:
      "Manage your subscription, update payment methods, and handle account settings.",
  },
];

const faqs = [
  {
    question: "How are Snowflake Scores calculated?",
    answer:
      "Snowflake Scores evaluate stocks across five dimensions: Value, Growth, Profitability, Health, and Dividend. Each dimension is scored from 0 to 5 based on key financial metrics like P/E ratio, revenue growth, ROE, debt-to-equity, and dividend yield. The overall score is a weighted average giving 25% to Growth, 25% to Profitability, 20% to Health, 20% to Value, and 10% to Dividend.",
  },
  {
    question: "How often is stock data updated?",
    answer:
      "Stock quotes refresh every 60 seconds during market hours. Company profiles and financial statements are updated every 24 hours. News articles refresh every 15 minutes. AI-powered analysis summaries are cached for 7 days and regenerated when significant changes occur, such as earnings releases or major price movements.",
  },
  {
    question: "What AI model powers the analysis?",
    answer:
      "Takovic uses Anthropic's Claude AI models. Stock summaries and deep analysis are generated by Claude Sonnet 4.6, while real-time sentiment classification uses Claude Haiku 4.5 for faster response times. All AI outputs include confidence indicators and should be used alongside your own research.",
  },
  {
    question: "Can I export my portfolio data?",
    answer:
      "Yes. Professional plan subscribers can export portfolio holdings, transaction history, and performance reports in both CSV and PDF formats. Navigate to your portfolio, click the export icon in the top-right corner, and select your preferred format and date range.",
  },
  {
    question: "How do I cancel my subscription?",
    answer:
      "You can cancel your subscription at any time from Settings > Billing > Manage Subscription. Your access will continue until the end of your current billing period. No partial refunds are issued, but you will not be charged again after cancellation.",
  },
];

// ---------------------------------------------------------------------------
// Shared input class
// ---------------------------------------------------------------------------

const searchInputClass =
  "h-10 w-full rounded-md border border-input bg-background pl-10 pr-3 text-sm shadow-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring";

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function HelpPage() {
  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h1 className="text-xl font-semibold text-foreground">Help Center</h1>
        <p className="text-sm text-muted-foreground">
          Get help with Takovic
        </p>
      </div>

      {/* Search bar */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <input
          type="text"
          className={searchInputClass}
          placeholder="Search for help articles..."
        />
      </div>

      {/* Category cards — 2x2 grid */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        {categories.map((cat) => {
          const Icon = cat.icon;
          return (
            <Card
              key={cat.title}
              className="transition-colors hover:bg-muted/30 cursor-pointer"
            >
              <CardContent className="p-5">
                <div className="flex items-start gap-3">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-primary/10">
                    <Icon className="h-4.5 w-4.5 text-primary" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium text-foreground">
                        {cat.title}
                      </p>
                      <span className="text-xs tabular-nums text-muted-foreground">
                        {cat.articles} articles
                      </span>
                    </div>
                    <p className="mt-1 text-xs text-muted-foreground leading-relaxed">
                      {cat.description}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* FAQ Section */}
      <div>
        <h2 className="mb-4 text-sm font-medium text-foreground">
          Frequently Asked Questions
        </h2>
        <Card>
          <CardContent className="p-0">
            <div className="divide-y divide-border/50">
              {faqs.map((faq, i) => (
                <div key={i} className="p-5">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-sm font-medium text-foreground">
                      {faq.question}
                    </p>
                    <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground" />
                  </div>
                  <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Still need help? */}
      <Card className="border-primary/20">
        <CardContent className="p-5 text-center">
          <div className="flex justify-center mb-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10">
              <Mail className="h-5 w-5 text-primary" />
            </div>
          </div>
          <p className="text-sm font-medium text-foreground">
            Still need help?
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            Reach out to us at{" "}
            <span className="font-medium text-foreground">
              support@takovic.com
            </span>
          </p>
          <div className="mt-4">
            <Button>
              <Mail className="mr-2 h-4 w-4" />
              Contact Support
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
